### ISSUE TITLE
feat: be able to run the project locally using the dev container

### ISSUE THREAD

**Issue by cre8ivejp** [bucketeer-io/bucketeer#134]
Currently, there is no way to run the project locally, making it hard for the contributors to contribute.
We have two gateways, and we deploy the microservices in Kubernetes via helm.

- api-gateway (Client SDK)
- web-gateway (Dashboard)

The api-gateway uses managed Google services such as Pubsub, Memorystore (Redis), CloudSQL (MySQL), and BigQuery. We also use Bigtable, Kafka, and Druid for real-time analysis, but we will replace them with BigQuery in January.

The web-gateway uses managed Google services such as Memorystore (Redis) and CloudSQL (MySQL).

**Comment by Rahul7794** [comment]
@cre8ivejp finding some issues setting up a project in Goland ide with protos. Did you guys face similar issues?

![Screen Shot 2022-12-26 at 6 19 35 pm](https://user-images.githubusercontent.com/26568100/209550913-694acb7c-2fbf-4263-a5d2-7c30cf4fa7a0.png)

Somehow my ide is not able to resolve the proto paths. I tried a few things from my end, did not work:

https://stackoverflow.com/questions/63526898/cannot-resolve-import-in-proto-file
https://youtrack.jetbrains.com/issue/IDEA-274732/Protocol-Buffers-plugin-is-not-working

**Comment by cre8ivejp** [comment]
@Rahul7794, sorry for the inconvenience. I will update the setup guide.

Please install the protoc version 3.18.1
https://github.com/protocolbuffers/protobuf/releases/tag/v3.18.1

Next, run the following commands.

```
make local-deps
make deps
make proto-go
make build
```

Let me know if it works.

**Comment by Rahul7794** [comment]
@cre8ivejp worked thanks :)

**Comment by Rahul7794** [comment]
@cre8ivejp I am able to run the emulator locally for pubsub and docker for redis, mysql but after all the local env is set which part of the application I should run to test the connectivity? 

When make build is done, there are a lot of executables being created under `/bin`
A few questions to be answered are:
- Which command to run to test the local env setup?
- If I want to test `api-gateway` what are the steps?

**Comment by cre8ivejp** [comment]
@Rahul7794 

> Which command to run to test the local env setup?
> If I want to test api-gateway what are the steps?

To test the api-gateway, we also will need the web-gateway because we need to create the following data.

- [Create a service token](https://github.com/bucketeer-io/bucketeer/tree/main/hack/generate-service-token)
- [Create a project](https://github.com/bucketeer-io/bucketeer/tree/main/hack/create-project)
- [Create an environment](https://github.com/bucketeer-io/bucketeer/tree/main/hack/create-environment)
- [Create an API key](https://github.com/bucketeer-io/bucketeer/tree/main/hack/create-api-key)
- Create a feature flag (For this step, it will be a bit more complicated because we don't have a script)

Maybe I can create some dummy data to insert in MySQL, so we don't need to run the scripts. I will need to check here.

Note: Even if we don't create a feature flag initially, it will work because it will send an empty response. I will try to make this script tomorrow. Usually, we do create it on the admin dashboard.

The api-gateway has two APIs that we want to test first.

#### GetEvaluations

It gets the feature flags data from Redis, and if there is no cache, it will try to get them from MySQL and save them in Redis for the next requests.
If there is no data in both, it will return zero evaluation.
Once it gets the feature flags, it will evaluate the user and return the evaluations.

Also, it publishes to PubSub, the user info separately.

You can check using the following curl (You need to change some fields)
If you call it without the API key, it will return a 403 error.

```
curl POST -vvv -k http://localhost:port/get_evaluations -H 'authorization: <API-KEY>' -H "Content-Type: application/json" -d '{"tag":"tag_name","user":{"id":"user-id","data":{"foo":"bar"}},"sourceId":"ANDROID"}'
```

#### RegisterEvents

All the events generated on the client SDK are reported using this API. 
The server checks the event ID and the timestamp before sending it to PubSub.
If there are no errors, it will return an empty map. If so, it will return the map with the event ID that failed and if this event is retriable or not.

```
curl -X 'POST' 'http://localhost:port/register_events' -H 'Content-Type: application/json' -H 'authorization: <API-KEY>' -d ' {
  "events": [                                
    {
      "id": "644a1222-ebb7-41c3-b7d6-61c30397d259",
      "event": {
        "featureId": "external-monitoring",
        "featureVersion": 2,
        "userId": "user-id",
        "variationId": "51354060-813b-4d5e-8ee2-30d197061215",
        "reason": {             
          "type": "DEFAULT"                                              
        },
        "timestamp": 1672129604,
        "@type": "type.googleapis.com/bucketeer.event.client.EvaluationEvent"
      }
    }
  ]
}';
```

Note: The timestamp must be within 24 hours.

**Comment by Rahul7794** [comment]
@cre8ivejp for MySQL an init script with table definition and 5-10 insert statement should be good for me to start the SQL docker

**Comment by cre8ivejp** [comment]
@Rahul7794 

> for MySQL an init script with table definition and 5-10 insert statement should be good for me to start the SQL docker

Ok, I will try to create a script tomorrow.

Also, to deploy the api-gateway service, you will need to configure some settings in the helm chart.
https://github.com/bucketeer-io/bucketeer/blob/main/manifests/bucketeer/charts/api-gateway/values.yaml

The api-gateway requests the following services when there is no cache in Redis.

https://github.com/bucketeer-io/bucketeer/blob/main/manifests/bucketeer/charts/environment/values.yaml
https://github.com/bucketeer-io/bucketeer/blob/main/manifests/bucketeer/charts/account/values.yaml
https://github.com/bucketeer-io/bucketeer/blob/main/manifests/bucketeer/charts/feature/values.yaml

**Comment by Rahul7794** [comment]
@cre8ivejp roger that

Is there a way I can run the web gateway locally in docker? If there is, then which part of the code base is needed to be built? or do I have to deploy to mini Kube, if yes then the repository has to be a local image name?

Please suggest if I am heading in the wrong direction. To fasten this process, if we can jump over zoom, that would be nice.

**Comment by cre8ivejp** [comment]
@Rahul7794 

Unfortunately, there is no easy way to deploy the web-gateway alone.
The api-gateway and the web-gateway both deploy by the helm chart application in Kubernetes.

We need to deploy the helm chart in the mini kube first. From there, we can fix the issues that will come up during the process.

The helm chart image is upload here.
https://github.com/bucketeer-io/bucketeer/pkgs/container/chart%2Fbucketeer

And the images that the helm chart uses are here.
https://github.com/orgs/bucketeer-io/packages

We can talk tomorrow on zoom from 14:00 (JST). Let me know what time works for you.

**Comment by Rahul7794** [comment]
Okay let me setup mini kube at my local and try to run these helm charts.

14.30 jst works for me.

**Comment by cre8ivejp** [comment]
@Rahul7794 

Ok.
I'll send you the zoom link tomorrow.
