### ISSUE TITLE
Dashboard crashes when switching experiments on the Experiment tab on the Feature details page

### ISSUE THREAD

**Issue by cre8ivejp** [bucketeer-io/bucketeer#140]
### How to reproduce

1 - Access the [link](http://localhost:8000/development/features/feature-flag-test-id/experiments?experimentId=6319e55c-895f-41e3-909d-68495eb0be9a)
2- Switch to experiment 2 on the select menu on the top left
3- After it is loaded, switch again to experiment 1
4- The dashboard becomes blank.

**Comment by bimalgrg519** [comment]
<img width="1403" alt="Screenshot 2023-01-08 at 6 37 46 @cre8ivejp M" src="https://user-images.githubusercontent.com/11039098/211197068-514f9a67-55f9-430c-bc59-ed520cd958bf.png">
@cre8ivejp  How can i add value to see chart?

**Comment by cre8ivejp** [comment]
@bimalgrg519 
We need to run an experiment to have those values.
I will add some values by today.
