### ISSUE TITLE
Auto Ops conditions is duplicated

### ISSUE THREAD

**Issue by cre8ivejp** [bucketeer-io/bucketeer#141]
When the user adds a new condition or operation in the Auto Ops tab after clicking on the `Submit` button, it reloads the page but doesn't clear the data used in the request. The `Submit` button should be disabled.

Because of that, if the user clicks again on the `Submit`, it will duplicate the data until the data used in the request is cleared.

**Comment by bimalgrg519** [comment]
I have added new condition/operation but submit button is still disable. Because of that i could not reproduce the issue.

**Comment by cre8ivejp** [comment]
@bimalgrg519 

Steps to reproduce

1- Add an operation with a Schedule condition (Schedule it one day ahead)
2- Click on submit button
3- Click on submit button again
4- Refresh the page, and you will see two operations

The problem is that after the request is made, it does not show a success message on the top right, and it's not clearing the request data in the code. That's probably the reason you can still click the submit button.

I found another bug.
If you try to delete an Operation, the submit button is still disabled.
Try to delete `Operation 1`.
https://localhost:8000/development/features/feature-flag-test-id/autoops

Please let me know if you confirm both issues.
