### ISSUE TITLE
feat: be able to check the audit log details

### ISSUE THREAD

**Issue by cre8ivejp** [bucketeer-io/bucketeer#804]
Currently, we can check who made the change, what entity changed, and what time it changed, but we can't see what values changed. It's impossible to track the changes, and there is no `diff` feature to compare the before/after changes, which makes it hard to manage the logs.

**Comment by kentakozuka** [comment]
Related https://github.com/bucketeer-io/bucketeer/issues/904
To add public API, we need to simplify web API, which fixes this issue, too.

**Comment by kentakozuka** [comment]
- [x] Feature
  - [ ] remove any commands
- [ ] Segment
- [ ] ...
